### PR TITLE
Add `filePath` option

### PR DESCRIPTION
**Pull request by karaggeorge**
Adds a `filePath` option which allows you to control where the file is created.

Will be needed for issues like https://github.com/wulkano/Kap/issues/871

### CODE REVIEW

**Comment by sindresorhus** [comment]
https://github.com/wulkano/aperture-node/pull/11

**Comment by karaggeorge** [comment]
So, should I add some kind of documentation? In this case, that is the desired behavior. People want this so if your computer/kap crashes, you at least have that file in a location you know, so maybe they can salvage it, so I don't think using the tmp and moving at the end would solve that

**Comment by sindresorhus** [comment]
Yes. Docs. Per https://github.com/wulkano/aperture-node/pull/7#discussion_r293724113.

> In this case, that is the desired behavior. People want this so if your computer/kap crashes, you at least have that file in a location you know, so maybe they can salvage it, so I don't think using the tmp and moving at the end would solve that

The point isn't that it solves that use-case. The point is that the recommended default should be temp and if an app wants, they can let the user customize it. Your computer crashing is an edge-case and it's better to document the temp location instead of an option, in my opinion.

**Comment by sindresorhus** [comment]
Bump

**Comment by sindresorhus** [comment]
Bump

**Comment by karaggeorge** [comment]
I don't think we need this anymore? I think we fixed this issue in Kap the right way. We could close until another need for it arises?

**Pull request closed without merging**
