### PR TITLE
Fix timeout error in some cases

### PR DESCRIPTION
**Pull request by billyct**
https://github.com/wulkano/Kap/issues/921#issuecomment-991641237

[Kap](https://github.com/wulkano/Kap) always show me `Error: Could not start recording within 5 seconds` when I'm trying to record

it works on my mac after I put the `onStart` event into `recorder.onStart` scope

Maybe it's because of the `onStart` event has been sent before `waitForEvent('onStart')` called in Electron env on my mac

### CODE REVIEW

**Comment by sindresorhus** [comment]
> Maybe it's because of the onStart event has been sent before waitForEvent('onStart') called in Electron env on my Mac

Then you're fixing it in the wrong place. The listener should be attached before the command is spawned.

**Comment by billyct** [comment]
I updated with the `onStart` listener attached before the command is spawned.

**Comment by sindresorhus** [comment]
And you have manually confirmed that it still resolves the problem for you even after the latest changes?

**Comment by billyct** [comment]
> And you have manually confirmed that it still resolves the problem for you even after the latest changes?

Yes, confirmed

**Comment by levrik** [comment]
Any timeline on when Kap will receive this fix?
Basically Kap completely broke for me. It doesn't matter how often I retry. It always fails due to this.

**Pull request merged**
